import OpenAI from "openai";
import type { BrandDnaData, Product } from "@/types";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export type VideoStyle = "ugc" | "lifestyle" | "product-hero";
export type VideoPlatform = "tiktok" | "instagram-reels" | "youtube-shorts";

export interface VideoScene {
  index: number;
  description: string;
  nano_prompt: string; // prompt for Nano Banana 2 to generate this frame
}

export interface VideoPromptOutput {
  scenes: VideoScene[]; // 5 scenes
  video_prompt: string; // full Seedance 2 prompt referencing @Image1-@Image6
  script: string;       // on-screen text / spoken lines
  hook: string;         // opening hook text
}

const STYLE_INSTRUCTIONS: Record<VideoStyle, string> = {
  ugc: `UGC (user-generated content) style. Authentic, handheld, real-person POV. Someone holding the product, talking to camera, showing results. No studio lighting — natural home/room light. Feels organic, not produced.`,
  lifestyle: `Lifestyle editorial. Clean but not sterile. Product in context of daily life. Person interacting with product naturally. Warm, aspirational, real-world setting.`,
  "product-hero": `Product hero. Product as the star. Cinematic close-ups, elegant movement, satisfying reveals. Can include hands but no face required. Studio or premium location setting.`,
};

const PLATFORM_ASPECT: Record<VideoPlatform, string> = {
  tiktok: "9:16",
  "instagram-reels": "9:16",
  "youtube-shorts": "9:16",
};

export function getVideoAspectRatio(platform: VideoPlatform): string {
  return PLATFORM_ASPECT[platform];
}

export async function generateVideoPrompt({
  dna,
  product,
  videoStyle,
  platform,
  duration,
  includesPerson,
}: {
  dna: BrandDnaData;
  product: Product;
  videoStyle: VideoStyle;
  platform: VideoPlatform;
  duration: 5 | 10 | 15;
  includesPerson: boolean;
}): Promise<VideoPromptOutput> {
  const aspectRatio = getVideoAspectRatio(platform);
  const numScenes = duration <= 5 ? 3 : duration <= 10 ? 4 : 5;

  const systemPrompt = `You are a video creative director for DTC brands.

You generate video concepts for Seedance 2 — an AI video model that takes multiple reference images and animates between them. Your job is to output:
1. ${numScenes} scene descriptions — each becomes a still frame generated by Nano Banana 2 image model
2. A Seedance 2 video_prompt — uses @Image1 through @Image${numScenes} to reference those frames, and @Image${numScenes + 1} to reference the actual product photo
3. A script — on-screen text lines or spoken dialogue for the video
4. A hook — the opening line/moment

Video style: ${STYLE_INSTRUCTIONS[videoStyle]}
Platform: ${platform} (${aspectRatio} vertical format)
Duration: ${duration} seconds
Person in video: ${includesPerson ? "Yes — a real person (creator/user) should appear in the scenes" : "No — product-focused, hands/product only, no face"}

LANGUAGE RULE: The script MUST be written in the brand's language: "${dna.language}". All scene descriptions and the video_prompt must be in English (they are technical prompts for image generators).

NANO BANANA PROMPT RULES for scenes:
- Each nano_prompt must be a complete visual description for a single still frame in ${aspectRatio} vertical format
- Describe brand colors visually (not hex), no font names
- Match the video style aesthetic consistently across all scenes
- For scenes with a person: describe their pose, expression, what they're doing — not their identity
- Do NOT include text overlays in scene prompts — those come from the script

VIDEO PROMPT RULES:
- Reference scenes as @Image1 through @Image${numScenes}
- Reference the product photo as @Image${numScenes + 1} — always include: "@Image${numScenes + 1} is the product — keep it exactly as shown in the reference photo, do not alter the product design or color"
- Describe the motion, camera movement, transitions between scenes
- Keep under 500 words total

OUTPUT: Valid JSON only, no markdown.

{
  "scenes": [
    { "index": 1, "description": "what happens in this scene", "nano_prompt": "full image gen prompt for this frame" },
    ...
  ],
  "video_prompt": "full Seedance 2 prompt with @Image refs",
  "script": "On-screen text or spoken dialogue for the full video",
  "hook": "Opening hook line (first 3-5 words)"
}`;

  const userMessage = `Brand: ${dna.name}
${dna.tagline ? `Tagline: ${dna.tagline}` : ""}
${dna.brand_story ? `Story: ${dna.brand_story}` : ""}
${dna.target_audience ? `Target audience: ${dna.target_audience}` : ""}
${dna.brand_personality ? `Personality: ${dna.brand_personality}` : ""}
${dna.customer_desires.length > 0 ? `Customer desires: ${dna.customer_desires.join(", ")}` : ""}
Colors: ${[dna.accent_color, dna.lettertype_color, dna.background_color].filter(Boolean).join(", ")}

Product: ${product.name}
${product.description ? `Description: ${product.description}` : ""}

Generate a ${duration}-second ${videoStyle} video for ${platform}. The video must hook immediately — first 2 seconds need to stop the scroll.`;

  const completion = await openai.chat.completions.create({
    model: "gpt-4o",
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userMessage },
    ],
    temperature: 0.8,
    response_format: { type: "json_object" },
  });

  const raw = completion.choices[0].message.content ?? "{}";
  const parsed = JSON.parse(raw) as VideoPromptOutput;
  return parsed;
}
